import {
    LayoutDashboard,
    BarChart3,
    Store,
    Users,
    FolderTree,
    Package,
    Boxes,
    Star,
    ShoppingCart,
    RotateCcw,
    Truck,
    CreditCard,
    Percent,
    FileText,
    Settings,
    UserCog,
    Shield,
    Plus,
    TrendingUp,
    Tag,
    Ticket,
    User,
    DollarSign,
    AlertCircle,
    Bell,
    Mail,
    Search,
    Calendar,
    Clock,
    Briefcase,
    Building2,
    Building,
    MapPin,
    Phone,
    Globe,
    Wallet,
    Landmark,
    Receipt,
    ClipboardList,
    LifeBuoy,
    HelpCircle,
    Info,
    CheckCircle2,
    CheckCircle,
    XCircle,
    AlertTriangle,
    Image as LucideImage,
    Trash2,
    Pencil,
    PlusCircle,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    ArrowRight,
    ArrowLeft,
    MoreHorizontal,
    MoreVertical,
    LogOut,
    Menu,
    Lightbulb,
    Zap,
    Printer,
    Sparkles,
    Share2,
    Stethoscope,
    CalendarCheck,
    CalendarX,
    ShieldCheck,
    CalendarClock,
    MessageSquare,
    Notebook,
    Instagram,
    Facebook,
    Linkedin,
    Twitter,
    Youtube,
    Contact,
    Camera,
    X,
    Medal,
    Trophy,
    Upload,
    File,
    Eye,
    Check,
    MousePointerClick,
    Map,
    MessageCircle,
    Music,
    Sun,
    Inbox,
    Send,
    CloudUpload,
    Bold,
    Italic,
    Headset,
    Banknote,
    Timer,
    Smile,
    Target,
    LucideIcon
} from 'lucide-react';


export const Icons: Record<string, LucideIcon> = {
    LayoutDashboard,
    BarChart3,
    Store,
    Users,
    FolderTree,
    Package,
    Boxes,
    Star,
    ShoppingCart,
    RotateCcw,
    Truck,
    CreditCard,
    Percent,
    FileText,
    Settings,
    UserCog,
    Shield,
    Plus,
    TrendingUp,
    Tag,
    Ticket,
    User,
    DollarSign,
    AlertCircle,
    Bell,
    Mail,
    Search,
    Calendar,
    Clock,
    Briefcase,
    Building2,
    Building,
    MapPin,
    Phone,
    Globe,
    Wallet,
    Landmark,
    Receipt,
    ClipboardList,
    LifeBuoy,
    HelpCircle,
    Info,
    CheckCircle2,
    CheckCircle,
    XCircle,
    AlertTriangle,
    Image: LucideImage,
    Trash2,
    Pencil,
    PlusCircle,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    ArrowRight,
    ArrowLeft,
    MoreHorizontal,
    MoreVertical,
    LogOut,
    Menu,
    Lightbulb,
    Logistics: Truck,
    Shop: Store,
    Inventory: Boxes,
    Finance: DollarSign,
    Sales: ShoppingCart,
    Services: Briefcase,
    Catalog: Package,
    Help: HelpCircle,
    Headset,
    Profile: User,
    Chart: BarChart3,
    Zap,
    Printer,
    Sparkles,
    Share2,
    Stethoscope,
    CalendarCheck,
    CalendarX,
    ShieldCheck,
    CalendarClock,
    Messages: MessageSquare,
    Invoices: Notebook,
    Instagram,
    Facebook,
    Linkedin,
    Twitter,
    Youtube,
    Contact,
    Camera,
    X,
    Medal,
    Trophy,
    Upload,
    File,
    Eye,
    Check,
    MousePointerClick,
    Map,
    MessageCircle,
    Music,
    Sun,
    Inbox,
    Send,
    CloudUpload,
    Bold,
    Italic,
    Banknote,
    Timer,
    Smile,
    Target
};

interface IconProps {
    name: string;
    className?: string;
}

export default function Icon({ name, className }: IconProps) {
    const IconComponent = Icons[name];

    if (!IconComponent) {
        return null;
    }

    return <IconComponent className={className} />;
}
